### ISSUE TITLE
Using latest neovim-package(pynvim) error

### ISSUE THREAD

**Issue by Shougo** [roxma/vim-hug-neovim-rpc#43]
The example is defx error message in Vim8.

```
[defx] Vim(pythonx):Traceback (most recent call last):
[defx] function defx#util#call_defx[2]..defx#start[1]..defx#initialize[1]..defx#init#_initialize[5]..defx#init#_channel[18]..yarp#core#request[1]..yarp#core#wait_channel[5]..yarp#core#jobstart[2]..yarp#pyx#init[13]..yarp#core#serveraddr[1]..neovim_rpc#serveraddr[19]..<SNR>42_py, line 1
```

It seems fails to execute the line.
https://github.com/roxma/vim-hug-neovim-rpc/blob/master/autoload/neovim_rpc.vim#L36

```vim
call s:py('import neovim_rpc_server')
```

**Comment by Shougo** [comment]
Error traceback is here.

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/shougo/work/vim-hug-neovim-rpc/pythonx/neovim_rpc_server.py", line 17, in <module>
    from neovim.api import common as neovim_common
ImportError: cannot import name 'common' from 'neovim.api' (/home/shougo/.local/lib/python3.7/site-packages/neovim/api/__init__.py)
```

**Comment by erw7** [comment]
How about the following patches? In my hands deoplete works.

```diff
diff --git a/pythonx/neovim_rpc_protocol.py b/pythonx/neovim_rpc_protocol.py
index cf4788e..3052c1c 100644
--- a/pythonx/neovim_rpc_protocol.py
+++ b/pythonx/neovim_rpc_protocol.py
@@ -11,7 +11,7 @@ import neovim_rpc_methods
 import threading
 import socket
 import time
-from neovim.api.common import decode_if_bytes
+from neovim.api import decode_if_bytes

 BUFFER_TYPE = type(vim.current.buffer)
 BUFFER_TYPE_ID = neovim_rpc_server_api_info.API_INFO['types']['Buffer']['id']
diff --git a/pythonx/neovim_rpc_server.py b/pythonx/neovim_rpc_server.py
index c536d89..d643c67 100644
--- a/pythonx/neovim_rpc_server.py
+++ b/pythonx/neovim_rpc_server.py
@@ -14,7 +14,10 @@ import threading
 import socket
 import time
 import subprocess
-from neovim.api import common as neovim_common
+try:
+    from neovim.api import common as neovim_common
+except:
+    from pynvim.api import common as neovim_common
 import neovim_rpc_protocol

 vim_error = vim.Function('neovim_rpc#_error')
```

**Comment by bfredl** [comment]
` neovim_common` is not used, you could just delete that line.

**Comment by Shougo** [comment]
@erw7 Thank you!  It works.
