### ISSUE TITLE
ImportError: undefined symbol: PyExc_ValueError

### ISSUE THREAD

**Issue by jonnyrobbie** [roxma/vim-hug-neovim-rpc#52]
I cannot seem to get this plugin to work. Below is some system information:

```
$ vim --version
VIM - Vi IMproved 8.1 (2018 May 18, compiled Mar 29 2019 20:08:59)
$ python3 --version
Python 3.7.3
$ uname -roms
Linux 5.0.5-arch1-1-ARCH x86_64 GNU/Linux
```
Vim:

`:echo has('pythonx')` `1`

`:echo has('python3)` `1`

`:set pyxversion?` `pyxversion=3 `

It should be noted that importing pynvim through standard python3 shell works without errors. But when I try to import pynvim through vim, this error happens:

`:python3 import pynvim`
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.7/site-packages/pynvim/__init__.py", line 11, in <module>
    from .msgpack_rpc import (ErrorResponse, child_session, socket_session,
  File "/usr/lib/python3.7/site-packages/pynvim/msgpack_rpc/__init__.py", line 10, in <module>
    from .session import ErrorResponse, Session
  File "/usr/lib/python3.7/site-packages/pynvim/msgpack_rpc/session.py", line 7, in <module>
    import greenlet
ImportError: /usr/lib/python3.7/site-packages/greenlet.cpython-37m-x86_64-linux-gnu.so: undefined symbol: PyExc_ValueError
Press ENTER or type command to continue
```

What could be the cause of this issue?

**Comment by jonnyrobbie** [comment]
I guess I should have looked a bit longer. This is a duplicate of this issue: https://github.com/roxma/vim-hug-neovim-rpc/issues/28 solved by uninstalling pip version of greenlet and installing the repository version of this package.
